[project]
name = "tectonic-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Archit Choudhary", email = "thearchitc@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-auth>=2.0.0",
    "google-api-python-client>=2.200.0",
    "google-auth-oauthlib>=1.5.0",
]
