# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='Where it came from, e.g. "Italian Gvt.", "HR"', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list, help_text='e.g. ["law", "template for 401K contribution"]')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('marks', models.JSONField(blank=True, default=dict, help_text='Free-form flags')),
                ('validity', models.CharField(blank=True, choices=[('', 'Not set'), ('useful', 'Useful'), ('old', 'Old'), ('invalid', 'Invalid'), ('awaiting_replacement', 'Awaiting replacement')], max_length=30)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('companies', models.ManyToManyField(blank=True, related_name='tagged_files', to='knowledge.customer')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='knowledge.drivefile')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('validity', models.CharField(blank=True, choices=[('', 'Not set'), ('useful', 'Useful'), ('old', 'Old'), ('invalid', 'Invalid'), ('awaiting_replacement', 'Awaiting replacement')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='knowledge.drivefile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='storage.note')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('meta', 'Meta'), ('note_added', 'Note Added'), ('note_reply', 'Note Reply'), ('note_validity', 'Note Validity'), ('version', 'Version')], max_length=30)),
                ('field', models.CharField(blank=True, max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='knowledge.drivefile')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='storage.note')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NoteMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in', to='knowledge.drivefile')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='storage.note')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('message', 'Message'), ('call', 'Call')], max_length=20)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField()),
                ('kind', models.CharField(choices=[('note', 'Note'), ('validity', 'Validity')], max_length=20)),
                ('suggested_note', models.TextField(blank=True)),
                ('suggested_validity', models.CharField(blank=True, choices=[('', 'Not set'), ('useful', 'Useful'), ('old', 'Old'), ('invalid', 'Invalid'), ('awaiting_replacement', 'Awaiting replacement')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.CharField(blank=True, max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO codes, e.g. ["BE"]')),
                ('see_all', models.BooleanField(default=False, help_text='Admins see every file')),
                ('companies', models.ManyToManyField(blank=True, related_name='members', to='knowledge.customer')),
            ],
            options={
                'verbose_name_plural': 'user access',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=64)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('file', 'number'), name='unique_file_version')],
            },
        ),
    ]
