# Generated by Django 6.1.1 on 2026-09-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Other names to detect in documents, e.g. ["Acme"]')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('review_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('completed', 'Completed')], default='not_requested', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='knowledge.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=200)),
                ('is_folder', models.BooleanField(default=False)),
                ('parent_ids', models.JSONField(blank=True, default=list)),
                ('path', models.CharField(blank=True, help_text='e.g. "HR Shared Drive / Payroll / Belgium"', max_length=2000)),
                ('shared_drive_id', models.CharField(blank=True, max_length=200)),
                ('shared_drive_name', models.CharField(blank=True, max_length=500)),
                ('owners', models.JSONField(blank=True, default=list, help_text='[{"name", "email", "role"}]')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='[{"type", "role", "email", "domain", "name"}]')),
                ('web_view_link', models.URLField(blank=True, max_length=1000)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('drive_modified_at', models.DateTimeField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=64)),
                ('trashed', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('content_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, help_text='ISO code; blank = not country-specific', max_length=2)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('contract', 'Contract'), ('guideline', 'Guideline'), ('faq', 'Faq'), ('template', 'Template'), ('memo', 'Memo'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('in_review', 'In Review'), ('draft', 'Draft'), ('archived', 'Archived'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('claims', models.JSONField(blank=True, default=list, help_text='[{"subject", "value", "text"}]')),
                ('supersedes_hint', models.CharField(blank=True, help_text='Title the document says it replaces', max_length=500)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('enrichment_source', models.CharField(blank=True, help_text='"rules" or "llm"', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='knowledge.customer')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['-drive_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='knowledge.case')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='evidence',
            field=models.ManyToManyField(related_name='cases', through='knowledge.CaseEvidence', to='knowledge.drivefile'),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expertise_tags', models.JSONField(blank=True, default=list, help_text='e.g. ["payroll", "BE"]')),
                ('active', models.BooleanField(default=True)),
                ('customers', models.ManyToManyField(blank=True, help_text='Customer history', related_name='experts', to='knowledge.customer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drivefile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to='knowledge.expert'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='knowledge.expert'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['file', 'index'],
                'constraints': [models.UniqueConstraint(fields=('file', 'index'), name='unique_chunk')],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('claim_a', models.TextField()),
                ('claim_b', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('file_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='knowledge.drivefile')),
                ('file_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='knowledge.drivefile')),
            ],
            options={
                'ordering': ['-detected_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('file_a', 'file_b', 'subject'), name='unique_conflict')],
            },
        ),
        migrations.AddConstraint(
            model_name='caseevidence',
            constraint=models.UniqueConstraint(fields=('case', 'file'), name='unique_case_evidence'),
        ),
    ]
